# Pre-commit hooks configuration - OPTIMIZED FOR SPEED
# Install: pip install pre-commit
# Setup: pre-commit install
# Run manually: pre-commit run --all-files
# Run slow checks: pre-commit run --hook-stage manual --all-files

repos:
  # General file fixes (FAST - Python-based)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: \.md$
      # - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ["--fix=lf"]

  # Python formatters (FAST - already in venv)
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        args: ["--line-length=100"]
        files: ^betlo/.*\.py$

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "100"]
        files: ^betlo/.*\.py$

  # Python linters (FAST - skip for commits, run manually)
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length=100", "--extend-ignore=E203,W503"]
        files: ^betlo/.*\.py$
        stages: [manual] # Only run manually, not on commit

  # SLOW HOOKS - Moved to manual stage (run with: pre-commit run --hook-stage manual)
  # These require Node.js/Go environments which are slow to install

  # YAML formatter (SLOW - requires Node.js)
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.12.0
    hooks:
      - id: pretty-format-yaml
        args: ["--autofix", "--indent", "2"]
        stages: [manual] # Only run manually

  # Markdown linter (SLOW - requires Node.js)
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: ["--fix"]
        stages: [manual] # Only run manually

  # Shell script formatter (SLOW - requires Go)
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.8.0-1
    hooks:
      - id: shfmt
        args: ["-i", "4", "-bn", "-ci", "-sr", "-w"]
        stages: [manual] # Only run manually
